namespace: jose_d
name: slurm
version: 0.0.31
readme: README.md
authors:
- Josef Dvoracek <jose@fzu.cz>

description: Collection containing ansible-ware interacting with slurm slurmctld daemon - HPC job manager - eg. draining and undraining nodes, getting node state, etc.

license_file: LICENSE

tags: [hpc,slurm]

dependencies: {}

repository: https://github.com/jose-d/ansible-jose_d-slurm
#documentation: http://docs.example.com
#homepage: http://example.com
issues: https://github.com/jose-d/ansible-jose_d-slurm/issues

build_ignore: []
